version: "3.9"

services:
  whatsapp-api:
    build: .
    container_name: whatsapp-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./wwebjs_auth:/app/wwebjs_auth # mantém sessão do WhatsApp entre reinícios
      - ./:/app
      - /app/node_modules
